name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up kernel headers
      run: sudo apt-get install -y linux-headers-$(uname -r)

    - name: Install dependencies
      run: sudo apt-get install -y build-essential

    - name: Build project
      run: make -C sources/transmitter/module

    - name: Run tests
      run: make -C sources/transmitter/tester
